### ISSUE TITLE
importing clients() fails

### ISSUE THREAD

**Issue by jinwald12** [PaulMcMillan/kismetclient#1]
when calling from "kismetclient import Client" the following error messages are returned:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/kismetclient-0.5-py2.6.egg/kismetclient/**init**.py", line 1, in <module>
    from kismetclient.client import Client
  File "/usr/local/lib/python2.6/dist-packages/kismetclient-0.5-py2.6.egg/kismetclient/client.py", line 115
    named_fields = {k: v for k, v in zip(field_names, fields)}

**Comment by PaulMcMillan** [comment]
Fixed here:
https://github.com/PaulMcMillan/kismetclient/commit/faee643d2c5c6cde9c36271943a34f3ceb9c25a5
